server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_rout
          uri: http://localhost:8102
#          uri: http://101.200.234.101:8102
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848?username=nacos&password=nacos
#    address: nacos://101.200.234.101:8848